### PR TITLE
feat: create Service Bus namespace

### LINKED ISSUE #2: feat: create Service Bus namespace
See [Terraform resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace).

The initial implementation only needs to take into account the required arguments for this resource.

### PR DESCRIPTION
**Pull request by sebastianlolv**
Create Service Bus Namespace with required arguments and added Terratest go files.

### CODE REVIEW

**Comment by sebastianlolv** [comment]
Tests pass 👍

**Review by hknutsen — COMMENTED** [review]
- Should we set a default value for the SKU? Perhaps basic for lowest cost?
- Should we investigate if there should be a diagnostic setting created for the namespace?

**Comment by sebastianlolv** [comment]
Will set default SKU. and a diagnostic setting is a good idea.

**Comment by sebastianlolv** [comment]
Tests passes 🥇

**Review by helenakallekleiv — APPROVED** [review]
Test pass and LGTM 👍🏼

**Pull request merged**
